artifact_uri: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/910991725571527681/709367a54cc04d0d9d4d3eb7d873994d/artifacts
end_time: 1762703453984
entry_point_name: ''
experiment_id: '910991725571527681'
lifecycle_stage: active
run_id: 709367a54cc04d0d9d4d3eb7d873994d
run_name: logreg_tfidf
source_name: ''
source_type: 4
source_version: ''
start_time: 1762703453886
status: 3
tags: []
user_id: Dung Tran
