artifact_uri: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/910991725571527681/e15eaa1ac7704552b02d771a19e43c29/artifacts
end_time: 1762701959475
entry_point_name: ''
experiment_id: '910991725571527681'
lifecycle_stage: active
run_id: e15eaa1ac7704552b02d771a19e43c29
run_name: logreg_tfidf
source_name: ''
source_type: 4
source_version: ''
start_time: 1762701959393
status: 3
tags: []
user_id: Dung Tran
