artifact_uri: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/922299336513761353/a8857f5d8a4c434ca20819e18823bac0/artifacts
end_time: 1762703183712
entry_point_name: ''
experiment_id: '922299336513761353'
lifecycle_stage: active
run_id: a8857f5d8a4c434ca20819e18823bac0
run_name: inference
source_name: ''
source_type: 4
source_version: ''
start_time: 1762703183639
status: 3
tags: []
user_id: Dung Tran
