artifact_location: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/910991725571527681
creation_time: 1762701254820
experiment_id: '910991725571527681'
last_update_time: 1762701254820
lifecycle_stage: active
name: TaskPriorityPrediction
