artifact_uri: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/910991725571527681/17ffcada6fc74ec7aa96e15c7b09d5a2/artifacts
end_time: 1762702255919
entry_point_name: ''
experiment_id: '910991725571527681'
lifecycle_stage: active
run_id: 17ffcada6fc74ec7aa96e15c7b09d5a2
run_name: logreg_tfidf
source_name: ''
source_type: 4
source_version: ''
start_time: 1762702255815
status: 3
tags: []
user_id: Dung Tran
