artifact_uri: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/910991725571527681/32f199fdccc14012967ec167dfd15731/artifacts
end_time: 1762702096499
entry_point_name: ''
experiment_id: '910991725571527681'
lifecycle_stage: active
run_id: 32f199fdccc14012967ec167dfd15731
run_name: logreg_tfidf
source_name: ''
source_type: 4
source_version: ''
start_time: 1762702096410
status: 3
tags: []
user_id: Dung Tran
