artifact_uri: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/910991725571527681/34942ba7f17a4e138c9a37a6b0256e95/artifacts
end_time: null
entry_point_name: ''
experiment_id: '910991725571527681'
lifecycle_stage: active
run_id: 34942ba7f17a4e138c9a37a6b0256e95
run_name: inference
source_name: ''
source_type: 4
source_version: ''
start_time: 1762702846246
status: 1
tags: []
user_id: Dung Tran
