artifact_uri: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/910991725571527681/7c8dc6b574c748afa3d07f75371ac0c9/artifacts
end_time: 1762701708418
entry_point_name: ''
experiment_id: '910991725571527681'
lifecycle_stage: active
run_id: 7c8dc6b574c748afa3d07f75371ac0c9
run_name: logreg_tfidf
source_name: ''
source_type: 4
source_version: ''
start_time: 1762701708346
status: 4
tags: []
user_id: Dung Tran
