artifact_uri: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/910991725571527681/4725d1a31e7a4c6caddc3dcc0427dab7/artifacts
end_time: 1762701740956
entry_point_name: ''
experiment_id: '910991725571527681'
lifecycle_stage: active
run_id: 4725d1a31e7a4c6caddc3dcc0427dab7
run_name: logreg_tfidf
source_name: ''
source_type: 4
source_version: ''
start_time: 1762701740877
status: 3
tags: []
user_id: Dung Tran
