artifact_uri: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/922299336513761353/7fd30bd58cd3489ab55694e5e96bbb8c/artifacts
end_time: 1762702928985
entry_point_name: ''
experiment_id: '922299336513761353'
lifecycle_stage: active
run_id: 7fd30bd58cd3489ab55694e5e96bbb8c
run_name: inference
source_name: ''
source_type: 4
source_version: ''
start_time: 1762702928939
status: 4
tags: []
user_id: Dung Tran
