artifact_uri: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/910991725571527681/85da63963dae4c83b543400acf566ed3/artifacts
end_time: 1762702062346
entry_point_name: ''
experiment_id: '910991725571527681'
lifecycle_stage: active
run_id: 85da63963dae4c83b543400acf566ed3
run_name: logreg_tfidf
source_name: ''
source_type: 4
source_version: ''
start_time: 1762702062251
status: 3
tags: []
user_id: Dung Tran
