artifact_location: file:C:/Users/dungtk/Documents/genestory/genestory_code_assignment/mlflow/922299336513761353
creation_time: 1762702812696
experiment_id: '922299336513761353'
last_update_time: 1762702812696
lifecycle_stage: active
name: inference_experiment
